GET http://localhost:8000/api/categories

################################################################################

GET http://localhost:8000/api/categories/f5aa1cef-f889-43cc-bb22-c3828aea654e

################################################################################

POST http://localhost:8000/api/create-category
Content-Type: application/json

{
    "categoryName": "Categoría 2"
}

################################################################################

PUT http://localhost:8000/api/update-category/604835c2-c8fb-4bd4-af54-d5f0f525f8e2
Content-Type: application/json

{
    "categoryName": "Categoría Actualizada"
}

################################################################################

DELETE http://localhost:8000/api/delete-category/604835c2-c8fb-4bd4-af54-d5f0f525f8e2
