GET http://localhost:8000/api/categories

################################################################################

GET http://localhost:8000/api/categories/f5aa1cef-f889-43cc-bb22-c3828aea654e

################################################################################

POST http://localhost:8000/api/create-category
Content-Type: application/json

{
    "categoryName": "Categoría 1"
}

################################################################################

PUT http://localhost:8000/api/update-category/349b417c-3870-4d01-b28b-a97271090b0d
Content-Type: application/json

{
    "categoryName": "Categoría Actualizada"
}

################################################################################

DELETE http://localhost:8000/api/delete-category/349b417c-3870-4d01-b28b-a97271090b0d
