GET http://localhost:8000/api/customers

################################################################################

GET http://localhost:8000/api/customers/5aab7011-f6da-4bdd-a6eb-78df5e8e0e8a

################################################################################

POST http://localhost:8000/api/create-customer
Content-Type: application/json

{
    "address": "Nueva direccion",
    "dni": "12345678",
    "user": "4e2f5bc8-bd74-4fa3-b6c7-d523c5127182"
}

################################################################################

PUT http://localhost:8000/api/update-customer/62b1762b-d83c-4e98-84fc-99214519f84b
Content-Type: application/json

{
    "address": "Nueva direccion actualizada",
    "dni": "12345678",
    "user": "4e2f5bc8-bd74-4fa3-b6c7-d523c5127182"
}

################################################################################

DELETE http://localhost:8000/api/delete-customer/62b1762b-d83c-4e98-84fc-99214519f84b
