GET http://localhost:8000/api/purchases-products

################################################################################

GET http://localhost:8000/api/purchases-products/9c1a8102-935f-4653-8a60-68478c2a7d45

################################################################################

POST http://localhost:8000/api/create-purchase-product
Content-Type: application/json

{
    "quantityProduct": 22,
    "purchase": "e8451502-6e3e-429a-add1-d1e9ee41fd5a",
    "product": "c64cb607-60b8-496a-a9c1-7763083da011"
}

################################################################################

PUT http://localhost:8000/api/update-purchase-product/7d8a634e-efdd-4708-8835-e1f40b4d752d
Content-Type: application/json

{
    "quantityProduct": 22,
    "purchase": "e8451502-6e3e-429a-add1-d1e9ee41fd5a",
    "product": "c64cb607-60b8-496a-a9c1-7763083da011"
}

################################################################################

DELETE http://localhost:8000/api/delete-purchase-product/7d8a634e-efdd-4708-8835-e1f40b4d752d
