GET http://localhost:8000/api/purchases

################################################################################

GET http://localhost:8000/api/purchases/4171e35d-4cef-4a98-bf13-23aca6fda701

################################################################################

POST http://localhost:8000/api/create-purchase
Content-Type: application/json

{
    "status": "true",
    "payment_method": "credit_card",
    "customer_id": "4171e35d-4cef-4a98-bf13-23aca6fda701",
}

################################################################################

PUT http://localhost:8000/api/update-purchase/7d8a634e-efdd-4708-8835-e1f40b4d752d
Content-Type: application/json

{
    "status": "false",
    "payment_method": "credit_card",
    "customer_id": "4171e35d-4cef-4a98-bf13-23aca6fda701",
}

################################################################################

DELETE http://localhost:8000/api/delete-purchase/7d8a634e-efdd-4708-8835-e1f40b4d752d
