GET http://localhost:8000/api/users

################################################################################

GET http://localhost:8000/api/user/a9f52b1b-61d4-4fcb-9630-ff9fbac02f54

################################################################################

POST http://localhost:8000/api/create-user
Content-Type: application/json

{
    "name": "test",
    "lastname": "test",
    "username": "test",
    "email": "test@test.com",
    "password": "test_password",
    "city": "ciudad",
    "providence": "provincia",
    "role": "customer"
}

################################################################################

PUT http://localhost:8000/api/update-user/832685e0-1ec4-4371-9b3c-0fbb5c238ce2
Content-Type: application/json

{
    "name": "actualizado",
    "lastname": "actualizado",
    "username": "actualizado",
    "email": "actualizado@actualizado.com",
    "password": "actualizado_password",
    "city": "ciudad",
    "providence": "provincia",
    "role": "user"
}

################################################################################

DELETE http://localhost:8000/api/delete-user/832685e0-1ec4-4371-9b3c-0fbb5c238ce2

################################################################################

GET http://localhost:8000/api/users/relation/a9f52b1b-61d4-4fcb-9630-ff9fbac02f54