GET http://localhost:8000/api/users

################################################################################

GET http://localhost:8000/api/user/a9f52b1b-61d4-4fcb-9630-ff9fbac02f54

################################################################################

POST http://localhost:8000/api/create-user
Content-Type: application/json

{
    "name": "test2",
    "lastname": "test2",
    "username": "test2",
    "email": "test2@test2.com",
    "password": "test2_password",
    "city": "ciudad",
    "providence": "provincia",
    "role": "user"
}

################################################################################

PUT http://localhost:8000/api/update-user/6f56b3be-1510-40e4-bee4-b9a799c460e6
Content-Type: application/json

{
    "name": "actualizado",
    "lastname": "actualizado",
    "username": "actualizado",
    "email": "actualizado@actualizado.com",
    "password": "actualizado_password",
    "city": "ciudad",
    "providence": "provincia",
    "role": "user"
}

################################################################################

DELETE http://localhost:8000/api/delete-user/6f56b3be-1510-40e4-bee4-b9a799c460e6

################################################################################

GET http://localhost:8000/api/users/relation/8547d5c5-c5ee-4588-995f-f7e27f7cf3b6