GET http://localhost:8000/api/users

################################################################################

GET http://localhost:8000/api/user/4171e35d-4cef-4a98-bf13-23aca6fda701

################################################################################

POST http://localhost:8000/api/create-user
Content-Type: application/json

{
    "name": "test",
    "lastname": "test",
    "username": "test",
    "email": "test@test.com",
    "password": "test_password",
    "city": "ciudad",
    "providence": "provincia"
}

################################################################################

PUT http://localhost:8000/api/update-user/7d8a634e-efdd-4708-8835-e1f40b4d752d
Content-Type: application/json

{
    "name": "actualizado",
    "lastname": "actualizado",
    "username": "actualizado",
    "email": "actualizado@actualizado.com",
    "password": "actualizado_password",
    "city": "ciudad",
    "providence": "provincia"
}

################################################################################

DELETE http://localhost:8000/api/delete-user/7d8a634e-efdd-4708-8835-e1f40b4d752d
